# Generated by Django 5.2.8 on 2025-12-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_remove_order_paid_at_order_payment_method_order_shop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('shop_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
